### ISSUE TITLE
Problema de permissões com a criação da base de dados

### ISSUE THREAD

**Issue by ttiagojm** [LiveDivulgador/Live-Divulgador#21]
Eu fiz merge da contribuição do @k30v1n, pois se tiver a base de dados criada não dá qualquer problema.

No entanto, ao apagar a base de dados e deixar o código criá-la por mim, retorna um problema de permissões:

```
Traceback (most recent call last):
  File "/Bots/Twitch Streamers/Live-Divulgador/env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "/Bots/Twitch Streamers/Live-Divulgador/env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InsufficientPrivilege: permission denied to create database


The above exception was the direct cause of the following exception:       

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import db
  File "/Bots/Twitch Streamers/Live-Divulgador/db.py", line 42, in <module>
    create_database(engine.url)
  File "/Bots/Twitch Streamers/Live-Divulgador/env/lib/python3.8/site-packages/sqlalchemy_utils/functions/database.py", line 579, in create_database
    connection.execute(text)
  File "/Bots/Twitch Streamers/Live-Divulgador/env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1248, in execute
    return self._exec_driver_sql(
  File "/Bots/Twitch Streamers/Live-Divulgador/env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1547, in _exec_driver_sql
    ret = self._execute_context(
  File "/Bots/Twitch Streamers/Live-Divulgador/env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
    self._handle_dbapi_exception(
  File "/Bots/Twitch Streamers/Live-Divulgador/env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
    util.raise_(
  File "/Bots/Twitch Streamers/Live-Divulgador/env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Bots/Twitch Streamers/Live-Divulgador/env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "/Bots/Twitch Streamers/Live-Divulgador/env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InsufficientPrivilege) permission denied to create database

[SQL: CREATE DATABASE streamers ENCODING 'utf8' TEMPLATE template1]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

O meu processo para criar um utilizador, base de dados e configurar as permissões, é o seguinte:

**Criar o utilizador**
``` sudo -u postgres createuser <nome> ```

**Criar base de dados**
``` sudo -u postgres createdb <nome da base de dados> ```

### Agora dentro do psql

**Criar uma password para o utilizador**
```ALTER USER <nome> WITH ENCRYPTED PASSWORD '<password>';```

**Garantir privilégios**
```GRANT ALL PRIVILEGES ON DATABASE <nome da base de dados> to <nome>;```

**Comment by k30v1n** [comment]
Oi Tiago desculpa a demora nisso aqui. Vo tentar dar uma olhada pra ver se consigo reproduzir.

**Comment by k30v1n** [comment]
Oi @ttiagojm , vi que o código já mudou bastante desde a ultima vez que tinha visto https://github.com/LiveDivulgador/Live-Divulgador/pull/18. 

Essa issue ainda é um problema?

**Comment by ttiagojm** [comment]
Realmente o pessoal da [aHubTech](https://github.com/aHub-Tech) reescreveu o bot todo.

Então creio que esta essa issue não seja mais um problema
